version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: python3 src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env
